contact: mbrush
contributors: null
creators: null
description: None
dosdp_tools_options: --obo-prefixes=true
edit_format: ttl
export_formats:
- owl
- obo
github_org: monarch-initiative
gzip_main: false
id: chr
import_group:
  directory: imports/
  disabled: false
  ids:
  - ro
  - so
  products:
  - description: null
    id: ro
    mirror_from: null
    rebuild_if_source_changes: true
    robot_settings: null
  - description: null
    id: so
    mirror_from: null
    rebuild_if_source_changes: true
    robot_settings: null
  rebuild_if_source_changes: true
import_pattern_ontology: false
license: Unspecified
namespaces: null
obo_format_options: ''
pattern_group: null
pattern_pipelines_group: null
primary_release: full
reasoner: ELK
release_artefacts:
- full
- base
repo: monochrom
report_fail_on: null
robot_java_args: ''
robot_settings: null
robot_version: null
robotemplate_group: null
subset_group: null
title: monochrom
travis_emails: null
uribase: http://purl.obolibrary.org/obo
use_dosdps: false
use_external_date: false
